export const USER_EVENTS = {
    TAB_EVENT: 'TAB_EVENT',
    MOUSE_ENTER_EVENT: 'MOUSE_ENTER_EVENT',
    MOUSE_LEAVE_EVENT: 'MOUSE_LEAVE_EVENT',
    PROBLEM_CHANGED_EVENT: 'PROBLEM_CHANGED_EVENT',
    PROBLEM_SENT_EVENT: 'PROBLEM_SENT_EVENT',
    SOLUTION_CODE_SENT_EVENT: 'SOLUTION_CODE_SENT_EVENT',
    SOLUTION_TEXT_SENT_EVENT: 'SOLUTION_TEXT_SENT_EVENT',
    SOLUTION_CHECKBOX_SENT_EVENT: 'SOLUTION_CHECKBOX_SENT_EVENT',
    SOLUTION_MATCH_SENT_EVENT: 'SOLUTION_MATCH_SENT_EVENT',
};
