export const USER_EVENTS = {
    TAB_EVENT: 'TAB_EVENT',
    MOUSE_ENTER_EVENT: 'MOUSE_ENTER_EVENT',
    MOUSE_LEAVE_EVENT: 'MOUSE_LEAVE_EVENT',
    PROBLEM_CHANGED_EVENT: 'PROBLEM_CHANGED_EVENT',
    PROBLEM_SENT_EVENT: 'PROBLEM_SENT_EVENT',
};
